### ISSUE TITLE
1.15 breaks gtk fonts and dark mode on hyprland

### ISSUE THREAD

**Issue by HishamAHai** [flatpak/xdg-desktop-portal-gtk#454] opened 2023-10-21 10:06 UTC
I'm on Arch linux and upated x-d-p-gtk from 1.14 to 1.15
I use it along x-d-p-hyprland as suggested in the hyprland wiki
After updating, all the gtk3/4 apps stopped respecting the dark theme, and font antialiasing seems to have no effects. font now is barely readable on a 4k monitor

**Comment by brianmercer** [comment] 2023-10-21 13:27
Yes. Lost dark mode on sway. I don't see any difference with fonts.

Both xdg-desktop-portal and xdg-desktop-portal-gtk services running without error under systemd.

Using this config since the upgrade to xdg-desktop-portal 1.18:
```
# ~/.config/xdg-desktop-portal/sway-portals.conf

[preferred]
default=wlr;gtk
```

**Comment by ebassi** [comment] 2023-10-21 15:28
Duplicate of #453

**Closed by ebassi** 2023-10-21 15:28 UTC
