### ISSUE TITLE
Odd "background activity" notifications appearing

### ISSUE THREAD

**Issue by allanday** [flatpak/xdg-desktop-portal-gtk#249] opened 2019-11-28 10:41 UTC
Since upgrading my Fedora installation to version 31, I have been receiving rather odd "Background activity" notifications, like these:

![image](https://user-images.githubusercontent.com/213068/69799632-94297680-11cb-11ea-93c9-b1ff441e9508.png)

These notifications seem to appear at random - never in response to something specific I've done. They appear in bunches of 2 or 3 at a time.

They have content like: Background activity, Telegram desktop is running in the background. This is plain wrong: the apps that they refer to are not running in the background - they are in the foreground. 

When I click on one of the notifications, the whole group magically disappears.

It's unclear what the notifications are for, or why I'm supposed to care about them.

**Comment by matthiasclasen** [comment] 2019-11-28 15:33
does this stop if you do:

```
dconf write /org/gnome/mutter/introspect true
```
And if you run

```
/usr/libexec/xdg-desktop-portal-gtk --replace --verbose
```
do you see any error messages when these notifications appear ?

**Comment by allanday** [comment] 2019-11-29 14:29
I saw 2 or 3 sets of these notifications, and I haven't seen any since. I assume that they are being shown once for a certain set of apps.

That makes testing a bit tricky. Do we know which apps will generate one of these notifications?

**Comment by hadess** [comment] 2019-11-29 14:58
Wouldn't this be the notification you get when applications try to access the "background mode" functionality? I mentioned to Allan that I would have expected an authorisation dialogue to show up, rather than a notification. If a notification shows up, I'd expect it to have an action button that launches the Application Settings for that application, so the background toggle is visible.

**Comment by allanday** [comment] 2019-11-29 15:51
I'm not clear to me why explicit authorization is necessary or desirable background apps. What's the user story here?

**Comment by hadess** [comment] 2019-11-29 16:19
Background applications can use the network and leak out usage while seemingly invisible, and they can also be the cause of battery drain or unexpected network usage.

So for privacy reasons, and battery saving, at least.

**Comment by hadess** [comment] 2019-11-29 16:31
This is especially important in our ecosystem as background data and resource usage isn't as carefully restricted as it can be on mobile OSes. For example, iOS expects application developers to mention which background modes they'd like to be eligible for, and then the OS will ask the user, on behalf of the application, the first time it wants to use one of those background modes.

See https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/updating_your_app_with_background_app_refresh
> If you prompt the user to enable [background mode] for your app, respect the user’s decision and don’t prompt a second time.

**Comment by allanday** [comment] 2019-11-29 17:01
> Background applications can use the network and leak out usage while seemingly invisible, and they can also be the cause of battery drain or unexpected network usage.
> 
> So for privacy reasons, and battery saving, at least.

Two problems there:
 - users don't know how much battery or network an app is going to use in advance
 - the availability of those resources changes over time, so a binary can/can't run in the background doesn't fit

The challenge I see with this whether an explicit authorization can ever be made to be meaningful to users. If we ask "should this app be able to run in the background", I can see a lot of people scratching their heads.

One thing I have thought about in the past is whether "run in the background" could/should be combined with autostart, which could potentially make the question a bit more meaningful.

(This is a bit different from being able to revoke the ability to run in the background, should an app misbehave.)

**Comment by hadess** [comment] 2019-11-29 18:40
> The challenge I see with this whether an explicit authorization can ever be made to be meaningful to users. If we ask "should this app be able to run in the background", I can see a lot of people scratching their heads.

It asks once, not multiple times, and you could also know that you only ever want a particular application to be "doing things" when you have it open and at no other point.

For example, you might only want your IRC client to run when it's visible, and never in the background.

Again, it's not as precise with our model because we can't filter network usage, or force a particular sandboxing feature that the app has access to to only work when it's in the foreground, but I think that it would certainly be the least surprising thing.

I mean, if running in the background without asking the user is fine, we probably don't need those notifications. But most of the cases in which we don't ask for permission in portals will be for cases where there's user intent. I doubt you clicked somewhere inside those 3 apps at once to get that result.

**Comment by matthiasclasen** [comment] 2019-11-30 22:14
> The challenge I see with this whether an explicit authorization can ever be made to be meaningful to users. If we ask "should this app be able to run in the background", I can see a lot of people scratching their heads.

It is not explicit authorization, it is really informational. "Hey, I've noticed that this app is running in the background. Is this your intention?"
 Its not a dialog that we present to the user. because there is no explicit user action here, it is just something we observe and inform the user about.
 
> One thing I have thought about in the past is whether "run in the background" could/should be combined with autostart, which could potentially make the question a bit more meaningful.

It is combined with autostart, as far as portal api is concerned. You can only ask for being autostarted if you also ask for being able to run in the background.

Btw, the easiest way to reproduce the notification is to explicitly run a flatpak without opening a window, like:

```
flatpak run --command=/bin/sh org.gnome.eog
```

and wait a while for the portal to notice this.

The biggest problem with the notification as-is is imo that clicking on it does not open anything, the notification just goes away. I would suggest to make it open the application settings for the app in question, but the control-center currently does not display the 'run in the background' permission. I think this coordination between portal permissions and control-center will be a bit of a problem going forward.

**Comment by matthiasclasen** [comment] 2019-11-30 23:12
This started out as an issue about "background activity" notifications being wrong (because the apps are not in the background). Now it is morphing into a general discussion of "background" UX. Can we separate these things?

**Comment by matthiasclasen** [comment] 2019-11-30 23:13
> Do we know which apps will generate one of these notifications?

Any application that the shell reports as running without any open windows, and which doesn't have an entry in the background permission table.

**Comment by matthiasclasen** [comment] 2019-11-30 23:31
https://github.com/flatpak/xdg-desktop-portal-gtk/pull/251 has a patch to launch the application panel for the application when the "background activity" notification is clicked. To make that meaningful, we need to display a "Can run in background" switch in the "System integration" section.

**Comment by allanday** [comment] 2019-12-03 11:40
Another bunch of these notifications appeared for me last night. It was like the other occasions: three notifications, shown at the same time, for apps that were running in the foreground. In this case, it was Rocket.Chat, Inkscape and Icon Library.

**Comment by allanday** [comment] 2019-12-03 11:47
> ... you could also know that you only ever want a particular application to be "doing things" when you have it open and at no other point.
> 
> For example, you might only want your IRC client to run when it's visible, and never in the background.

If you close an app and get a dialog that says "Polari wants to carry on running after you close the window" that's one thing. It's somewhat clear why a messaging app might want to run all the time.

(Although, we did actually try this approach for Polari, and we only got negative feedback.)

For many of the apps that I'm getting notifications for, the reason why they might want to run in the background not clear (this includes Icon Library, Inkscape and Gnote).

Another problematic part of this is: what happens if I click on the notification's "forbid" button? I have no idea.

**Comment by matthiasclasen** [comment] 2019-12-04 17:01
In the meantime, the background information is now available in flatpak ps as well:

```
$ ./flatpak ps --columns=instance,pid,application,active,background
Instance   PID    Application          Active Background
3063924985 589495 org.gnome.eog               🗸
2301427850 473568 org.telegram.desktop 🗸
2015053394 385449 org.gnome.Polari
```

**Comment by matthiasclasen** [comment] 2019-12-10 20:23
This should be fixed in the next release.

**Closed by matthiasclasen** 2019-12-10 20:23 UTC

**Comment by jimmac** [comment] 2020-02-20 09:39
I came late to the party, but I've started getting these. Is 3.36 release going to suffer from these, or is this gone for good?

**Comment by ptomato** [comment] 2020-04-20 18:28
Is there an issue open somewhere to discuss the background monitor UX in general?

**Comment by felipeborges** [comment] 2020-04-21 08:15
> Is there an issue open somewhere to discuss the background monitor UX in general?

I recall https://wiki.gnome.org/Design/Whiteboards/BackgroundApps#Discussion but it hasn't been updated lately.

**Comment by allanday** [comment] 2020-04-21 08:51
> Is there an issue open somewhere to discuss the background monitor UX in general?

You can open an issue against [os-mockups](https://gitlab.gnome.org/Teams/Design/os-mockups/), if you want to have a design-focused discussion.

**Comment by ptomato** [comment] 2020-08-11 18:54
I have been meaning to open that issue for quite a long time, but it seems that the UX improved quite a lot between GNOME 3.34 and 3.36, such that I was no longer entirely at a loss for what the notification wanted from me.

It would still be nice if applications could indicate why they wanted background access, but :shrug:
