### ISSUE TITLE
Allow Window sharing in the ScreenCast portal

### ISSUE THREAD

**Issue by tintou** [flatpak/xdg-desktop-portal-gtk#204] opened 2019-05-29 07:45 UTC
The portal actually has the interface to allow it and some apps (e.g. Chrome) actually support it, so it would be nice to have this implemented in the gtk portal.

**Comment by tintou** [comment] 2019-06-14 12:57
For info, this is where you can find that there is indeed an issue in this repository https://github.com/flatpak/xdg-desktop-portal-gtk/blob/b2b5ede150e7dd42361b9f9b7eccc056c188155c/src/screencast.c#L319

**Comment by jadahl** [comment] 2019-06-14 13:36
Here is the preliminary ![mockup](https://gitlab.gnome.org/Teams/Design/os-mockups/raw/master/portals/screen-sharing-remote-desktop.png) done by Alan. See https://gitlab.gnome.org/GNOME/gnome-shell/issues/828.

**Comment by allanday** [comment] 2019-06-14 17:46
It's worth noting that the major browsers provide their own dialog for screen sharing. This can result in the user being asked twice if the desktop has its own dialog.

I personally feel that browsers should possibly be exempt from this type of portal.

**Comment by Yajo** [comment] 2019-06-17 08:34
> I personally feel that browsers should possibly be exempt from this type of portal.

Or disable their own if running under wayland...

**Comment by tpopela** [comment] 2019-06-17 08:53
> > I personally feel that browsers should possibly be exempt from this type of portal.
> 
> Or disable their own if running under wayland/flatpak...

There are some problems with that - see https://gitlab.gnome.org/GNOME/gnome-shell/issues/828#note_425826 and below. In short their dialog provides an extra and useful functionality - it allows to share only one tab of the browser.

**Comment by jadahl** [comment] 2019-06-17 09:05
Would just like to point out that it's far from as simple from making them "exempt" from this type of dialog, since there is no portable way to allow third party applications to introspect the whole desktop environment, which is what such a dialog needs. We'd have to invent a lot of complicated portal APIs and effectively allow browsers to violate the Wayland "every client lives in isolation" feature.

**Comment by tpopela** [comment] 2019-06-17 09:47
Yes, I know that it isn't simple, but it would be nice if we could involve the Chromium and Firefox developers/designers in this discussion as well.

**Comment by albfan** [comment] 2019-06-20 09:38
screen sharing right now ask you twice, so I think we can live with that for a while.

Indeed, xdg-desktop-portal will ask you what screens to share (or apps in this case) and then browser will make you choice from those "allowed" to share screens (or apps). There're open issues to remember your choice on that, and after a first selection, it shouldn't ask twice anymore, isn't it?

Can anyone expose a tentative implementation to share open apps? I would work on this if I have any initial guidance

**Comment by jadahl** [comment] 2019-06-20 09:51
@albfan to add window sharing use the `org.gnome.Shell.Introspect` D-Bus API to get information about sharable windows (`org.gnome.Shell.Introspect.GetWindows`). The same API is used by the background portal implementation to retrieve running applications.

**Comment by albfan** [comment] 2019-06-20 14:59
Ok, I enabled gnome-shell instrospection:

    gsettings set org.gnome.shell introspect true

and ask for open windows:

    dbus-send --session --type=method_call --dest=org.gnome.Shell --print-reply /org/gnome/Shell/Introspect org.gnome.Shell.Introspect.GetWindows

```
method return time=1561042402.547556 sender=:1.13 -> destination=:1.2908 serial=21265 reply_serial=2
   array [
      dict entry(
         uint64 1442764654
         array [
            dict entry(
               string "app-id"
               variant                   string "terminator.desktop"
            )
            dict entry(
               string "client-type"
               variant                   uint32 0
            )
            dict entry(
               string "is-hidden"
               variant                   boolean false
            )
            dict entry(
               string "has-focus"
               variant                   boolean true
            )
            dict entry(
               string "width"
               variant                   uint32 1366
            )
            dict entry(
               string "height"
               variant                   uint32 768
            )
            dict entry(
               string "title"
               variant                   string "alberto@archlinux-alberto: ~"
            )
            dict entry(
               string "wm-class"
               variant                   string "terminator"
            )
         ]
      )
      dict entry(
         uint64 1442764715
         array [
            dict entry(
               string "app-id"
               variant                   string "org.gnome.Polari.desktop"
            )
            dict entry(
               string "client-type"
               variant                   uint32 0
            )
            dict entry(
               string "is-hidden"
               variant                   boolean false
            )
            dict entry(
               string "has-focus"
               variant                   boolean false
            )
            dict entry(
               string "width"
               variant                   uint32 1366
            )
            dict entry(
               string "height"
               variant                   uint32 768
            )
            dict entry(
               string "title"
               variant                   string "cee"
            )
            dict entry(
               string "wm-class"
               variant                   string "polari"
            )
         ]
      )
   ]
```

I suppose I have to do something with those `uint64 1442764715`, but not sure what.

My idea is to implement a fake app streaming list and then connect to windows later

**Comment by matthiasclasen** [comment] 2019-06-20 17:09
there's code in xdg-desktop-portal-gtk that handles this data:

https://github.com/flatpak/xdg-desktop-portal-gtk/blob/master/src/background.c#L43

**Comment by matthiasclasen** [comment] 2019-06-20 17:12
> There are some problems with that - see https://gitlab.gnome.org/GNOME/gnome-shell/issues/828#note_425826 and below. In short their dialog provides an extra and useful functionality - it allows to share only one tab of the browser.

Browsers _could_ handle that better if they wanted:

1) pop up their own dialog that asks ' share this tab or a window/screen ?'
2) if the choice is 'window/screen', call the portal
3) use the result without further questions

The problem is really browsers insisting that they are the only thing that matters and the rest of the world has to bend to their will.

**Comment by tpopela** [comment] 2019-06-21 04:44
> > There are some problems with that - see https://gitlab.gnome.org/GNOME/gnome-shell/issues/828#note_425826 and below. In short their dialog provides an extra and useful functionality - it allows to share only one tab of the browser.
> 
> Browsers _could_ handle that better if they wanted:
> 
> 1. pop up their own dialog that asks ' share this tab or a window/screen ?'
> 2. if the choice is 'window/screen', call the portal
> 3. use the result without further questions
> 
> The problem is really browsers insisting that they are the only thing that matters and the rest of the world has to bend to their will.

No, I think that the main reason is that no-one approach them to discuss that with them. The designed the dialog around the APIs that were available at the time - the X ones and now we should discuss with them how to do so with the new APIs/approaches/workflows. That's why I wrote that we should involve the Chromium and Firefox developers/designers in this discussion as well and personally tried to contact the Chromium ones.

**Comment by albfan** [comment] 2019-06-21 05:11
That sounds great, everybody is trying to improve this, so any implementation will allow us to iterate on UI/UX.

I tried to contact too crew from chromium.

**Comment by matthiasclasen** [comment] 2019-06-21 12:10
The other way to avoid the second xdg-desktop-portal dialog is to keep around the pipewire remote they used for obtaining the screenshot, and if the user choses that option, just keep using it.

**Comment by tpopela** [comment] 2019-06-21 12:12
> The other way to avoid the second xdg-desktop-portal dialog is to keep around the pipewire remote they used for obtaining the screenshot, and if the user choses that option, just keep using it.

We were thinking about that with Jan Grulich as well, but I didn't found an easy way to do so in Chromium.

**Comment by matthiasclasen** [comment] 2019-06-21 12:14
It has also been suggested that we could recognize the situation, and avoid the second dialog on our end.

But I don't think that can really work. It essentially amounts to assuming a specific workflow on the other side, and would break as soon as the browser ui changes (and it alsmost certainly will). It will already be broken for cases where the user makes a mistake and quickly wants to correct it:

a) user starts screen sharing in bluejeans
b) quickly recognizes that a 'bad' window is in the shared content
c) cancels and start over
d) we assume the portal call we get is soon enough after the initial one that we should just return the same choice without a dialog
e) bad window is shared again

**Comment by matthiasclasen** [comment] 2019-06-21 12:42
A browser ui that wants to show a screenshot of each window is basically unimplementable with the portal. We don't have a 'give me a screenshot/stream for this window' api, and the we don't offer sandboxed apps an api to enumerate windows (nor do we want to).

**Comment by jadahl** [comment] 2019-06-24 09:05
FWIW, I started on this a while ago, but it's not that far along yet, mostly preparation of some UI reshuffle:

https://github.com/jadahl/xdg-desktop-portal-gtk/commits/wip/screen-cast-window

**Comment by albfan** [comment] 2019-06-24 12:14
@jadahl That's great, can we see a screenshot of how it looks like right now?. Apart from implement it (I understoold it will be a text list) designers can suggest how better approach it, or if windows streaming can be helpul (although not available right now). @matthiasclasen just thinking in several terminals open or several gimp apps) windows will not be that easy to choose as screens.

**Comment by jadahl** [comment] 2019-06-24 12:42
@albfan it's mostly adding the switcher while keeping the monitor sharing intact.

Here are two screenshots, of whats there:

![Screenshot from 2019-06-24 14-40-40](https://user-images.githubusercontent.com/46741/60019473-3928ac00-968e-11e9-9dae-e9c4289cca9e.png)
![Screenshot from 2019-06-24 14-40-45](https://user-images.githubusercontent.com/46741/60019479-3d54c980-968e-11e9-9d03-cf5746cf648d.png)

**Comment by albfan** [comment] 2019-07-10 17:40
I have the code to retrieve the window class and title from dbus. Would be great if at least we have a way to paint the window icon (maybe from wm-class):

Right now this is a dialog hell as it raises two dialogs (one for window and other for monitors)

![dialog hell](https://user-images.githubusercontent.com/220968/60991197-5924c480-a34a-11e9-8229-a72d342e79a0.png)

NOTE: the window list is still a fake list, and items are not well aligned

**Comment by matthiasclasen** [comment] 2019-07-10 20:53
nice! It should be fairly straightforward to get the icons for flatpaked apps, since we enforce app-id = icon-name.

**Comment by matthiasclasen** [comment] 2019-07-10 22:51
it might be a bit more challenging to ask the shell for a thumbnail of every window

**Comment by albfan** [comment] 2019-07-11 06:33
@matthiasclasen I think so. https://github.com/albfan/dbus-getwindows match with dbus calls inside xdg-desktop-portal-gtk so should be easy to port the code, retrieve: titles, app-id and get the icon as:

```
g_desktop_app_info_new(app_id)
g_desktop_app_info_get_string(app_info, "Icon")
```

Will check around for usages of that to retrieve the icon and add to listbox.

@jadahl show me "dialog hell" is just d-bus call setup (See https://github.com/jadahl/xdg-desktop-portal-gtk/pull/1#issuecomment-510346646) so I think that part is on @tpopela field (if there's any chance to ask permission in other way)

Once that is on place, we can think how useful would be to have thumbnails or any kind of cache to avoid asking for permissions (in this session, forever, until 15 min or the like) Maybe not so problematic as expected.

**Comment by albfan** [comment] 2019-07-11 06:39
For anyone wanting to hack on this:

- [xdp-screen-cast.py](https://gitlab.gnome.org/snippets/19) Modify types to ask for both permissions at same time.

- [xdg-desktop-portal-gtk for AUR](https://github.com/albfan/aur-xdg-desktop-portal-gtk-git)

or

```
NOCONFIGURE=1 ./autogen.sh
./configure --prefix=/usr --libexecdir=/usr/lib
make
sudo make install
```

to install xdg-desktop-portal-gtk

NOTE: Remember to kill xdg-desktop-portal-gtk after each install, to use the fresh one:

    kill -9 $(ps -ef | grep xdg-desktop-portal-gt[k]|awk '{print $2}')

**Comment by albfan** [comment] 2019-07-11 09:58
![fake window list](https://user-images.githubusercontent.com/220968/61041736-21159400-a3d3-11e9-8ab1-25f118ff6163.png)

- [ ] We are just a dbus call away from this. https://github.com/albfan/dbus-getwindows 

I will review style and code organization with @jadahl before submit PR here

**Comment by matthiasclasen** [comment] 2019-07-11 14:25
thank you very much for working on this

**Comment by albfan** [comment] 2019-07-11 15:14
![listing windows available](https://user-images.githubusercontent.com/220968/61062740-09ec9b80-a3ff-11e9-8d92-18f628e30b5e.png)

- [ ] open stream for window https://gitlab.gnome.org/GNOME/mutter/blob/master/src/org.gnome.Mutter.ScreenCast.xml#L107

Will open the PR when streaming is working. I expect lot of corrections about code structure, memory management and similar.

**Comment by albfan** [comment] 2019-07-15 17:18
I'm glad to inform all of you this feature is working. I'm doing review with @allanday and @jadahl before open PR here.

@tpopela I'm using a screencast python script to select all sources in just one dialog, can we revisit what chrome is asking for so it ask just in one dialog? the key is to pass `multiple: TRUE` to dbus service.

**Comment by tpopela** [comment] 2019-07-16 04:32
@albfan We will try to look at it together with @grulja, but no ETA currently.

**Comment by albfan** [comment] 2019-07-24 12:42
@tpopela using this for a while:

- chrome starts a dialog, which ask for screen/windows permissions
- another dialog (xdg-desktop-portal) ask for screen permissions
- another dialog (xdg-desktop-portal) ask for windows permissions
- the chrome dialog shows the stream on those screen and windows selected
- once you select one of them, another dialog ask again for permission to do the real screencast

**Comment by tpopela** [comment] 2019-09-17 10:38
We came up with a plan together with @grulja .

We will create a new object in Chromium that will do the initialization and show the portal asking for available screens and windows (request them on the same time to get only one confirmation dialog).

THEN:
Based on the selected content from the xdg-desktop-portal dialog we will create a desired WebRTC capturer (a DesktopCapturer or the WindowCapturer one) and start the capture.

OR:
If there was nothing selected in the dialog, the original Chrome dialog will be shown, but only with the “Chrome Tab” tab. The reason for that is that as the users didn’t choose anything previously in the xdg-desktop-portal dialog, they just want to share the Chrome tab.

Once the above is implemented, only one dialog will be presented to the user in case that he wants to share the screen or window OR two dialogs if he wants to share the browser’s tab.

 What would help the user is some sort of preview for the windows and screens in the xdg-desktop-portal - would that be possible @jadahl and @allanday ?

**Comment by jadahl** [comment] 2019-09-17 12:26
> What would help the user is some sort of preview for the windows and screens in the xdg-desktop-portal - would that be possible @jadahl and @allanday ?

The plan is to eventually show previews into the portal UI yes, but it needs new methods for preparing the previews and handing them over to the portal process.

**Comment by matthiasclasen** [comment] 2019-09-17 14:34
We discussed some alternatives for getting thumbnails from the shell to the portal

**Comment by matthiasclasen** [comment] 2019-10-05 14:20
I think I'll close this now, as we have window selection

**Closed by matthiasclasen** 2019-10-05 14:20 UTC
