### ISSUE TITLE
1.15.0 broke GTK apps' cursor and font on KDE Plasma

### ISSUE THREAD

**Issue by medmedin2014** [flatpak/xdg-desktop-portal-gtk#455] opened 2023-10-21 11:10 UTC
Upgrading to 1.15.0 made my GTK apps to have big cursor with wrong window control buttons, and the font appears without antialiasing
![Screenshot_20231021_120900](https://github.com/flatpak/xdg-desktop-portal-gtk/assets/7027319/d3b21300-28d3-4757-8cb4-16203e714ecf)
![Screenshot_20231021_120927](https://github.com/flatpak/xdg-desktop-portal-gtk/assets/7027319/a9f8460b-9717-4ac0-af5c-b0d49cbf787b)

**Comment by TensoonTheFaceDancer** [comment] 2023-10-21 13:42
Got the same problem. I'm using Arch Linux with KDE Plasma on Wayland. Are there any quick fixes available?

**Comment by ebassi** [comment] 2023-10-21 15:28
Duplicate of #453

**Closed by ebassi** 2023-10-21 15:28 UTC
