### ISSUE TITLE
Error 71 (Protocol error) dispatching to Wayland display

### ISSUE THREAD

**Issue by mcatanzaro** [flatpak/xdg-desktop-portal-gtk#130] opened 2018-05-03 21:04 UTC
xdg-desktop-portal-gtk-0.11-1.fc28, with gtk3-3.22.30-1.fc28, quits immediately when the file choose portal is used. To reproduce, run `/usr/libexec/xdg-desktop-portal-gtk -r`, then open Epiphany (as a flatpak) and press Ctrl+O.

Result is: `Error 71 (Protocol error) dispatching to Wayland display`

**Comment by jadahl** [comment] 2018-05-04 13:04
The error is
```
[4101298.880] wl_display@1.error(zxdg_imported_v1@35, 0, "set_parent_of was called with an invalid child")
```

**Comment by jadahl** [comment] 2018-05-04 13:08
Looks like a mutter issue. Mind opening a bug report?

**Comment by mariospr** [comment] 2018-05-04 13:58
> Looks like a mutter issue. 

Indeed, at least doesn't look like an issue in the portal backend. FWIW, I just upgraded to Fedora 28 explicitly to test this problem and I could reproduce it on a Wayland session, but not on a X.org one (where things work fine).

> Mind opening a bug report?

Sure: https://gitlab.gnome.org/GNOME/mutter/issues/138

Closing this issue here then

**Closed by mariospr** 2018-05-04 13:58 UTC
